/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Eployee;

import DAO.NhanVienDAO;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modal.NhanVien;

/**
 *
 * @author Minh
 */
public class accountScreen extends javax.swing.JFrame {

    NhanVienDAO NV = new NhanVienDAO();
    mainScreen ms;
    private String currentAvatarPath = "";
    
    /**
     * Creates new form productFrame
     */
    public accountScreen(mainScreen m) {
        initComponents();
        ms =m;
        setLocationRelativeTo(null);
        loadScreen();
        
    }

    private void loadAccountInfo() {
        NhanVien nv = NV.getOne(ms.staffId);

        tfMa.setText(nv.getMaNhanVien().toString());
        tfMa.setEditable(false);

        tfTen.setText(nv.getHoTen());
        tfTen.setEditable(false);

        cbbChucVu.setSelectedItem(nv.getChucVu());
        cbbChucVu.setEnabled(false); // ComboBox dùng setEnabled

        tfNgaySinh.setText(nv.getNgaySinh());
        tfNgaySinh.setEditable(false);

        tfDienThoai.setText(nv.getSoDienThoai());
        tfDienThoai.setEditable(false);

        tfEmail.setText(nv.getEmail());
        tfEmail.setEditable(false);

        tfGioiTinh.setText(nv.getGioiTinh() ? "Nam" : "Nữ");
        tfGioiTinh.setEditable(false);

        tfDiaChi.setText(nv.getDiaChi());
        tfDiaChi.setEditable(false);

        tfNgayVaoLam.setText(nv.getNgayTuyenDung());
        tfNgayVaoLam.setEditable(false);

        tfIDEditPass.setText(nv.getMaNhanVien().toString());
        tfIDEditPass.setEditable(false);

        if (nv.getAnh()!=null) {
            URL imageUrl = getClass().getResource(nv.getAnh());
            ImageIcon icon = new ImageIcon(imageUrl);
            Image i = icon.getImage().getScaledInstance(120, 170, Image.SCALE_SMOOTH);
            JButton btn = new JButton("");
            btnIMGInfo.setIcon(new ImageIcon(i));
        }
        tfID.setText(nv.getMaNhanVien().toString());
        tfName.setText(nv.getHoTen());
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(nv.getNgaySinh());
            dtpk.setDate(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
        tfPhone.setText(nv.getSoDienThoai());
        tfEmailEdit.setText(nv.getEmail());
        tfAdress.setText(nv.getDiaChi());
    }

    private void loadRoles() {
        cbbChucVu.removeAllItems();
        for(String x : NV.getPosition())
            cbbChucVu.addItem(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAcc = new javax.swing.JPanel();
        pnInfo = new javax.swing.JPanel();
        lbTitleInfo = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        TablePane = new javax.swing.JTabbedPane();
        pnAccInfo = new javax.swing.JPanel();
        jlabel6 = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        jlabel7 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        tfMa = new javax.swing.JTextField();
        tfTen = new javax.swing.JTextField();
        tfDienThoai = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jlabel10 = new javax.swing.JLabel();
        jlabel11 = new javax.swing.JLabel();
        tfNgayVaoLam = new javax.swing.JTextField();
        jlabel12 = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        jlabel24 = new javax.swing.JLabel();
        tfNgaySinh = new javax.swing.JTextField();
        btnIMGInfo = new javax.swing.JButton();
        jlabel25 = new javax.swing.JLabel();
        tfGioiTinh = new javax.swing.JTextField();
        pnEditAccInfo = new javax.swing.JPanel();
        jlabel18 = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        jlabel19 = new javax.swing.JLabel();
        jlabel20 = new javax.swing.JLabel();
        jlabel21 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfEmailEdit = new javax.swing.JTextField();
        jlabel22 = new javax.swing.JLabel();
        jlabel23 = new javax.swing.JLabel();
        btnSaveEdit = new javax.swing.JButton();
        btnReloadEdit = new javax.swing.JButton();
        jlabel26 = new javax.swing.JLabel();
        cbbGender = new javax.swing.JComboBox<>();
        dtpk = new com.toedter.calendar.JDateChooser();
        pnSecurity = new javax.swing.JPanel();
        jlabel13 = new javax.swing.JLabel();
        jlabel15 = new javax.swing.JLabel();
        tfIDEditPass = new javax.swing.JTextField();
        jlabel16 = new javax.swing.JLabel();
        btnSavePass = new javax.swing.JButton();
        btnReLoadPass = new javax.swing.JButton();
        jlabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfConfirmPass = new javax.swing.JPasswordField();
        tfNewPass = new javax.swing.JPasswordField();
        tfOldPass = new javax.swing.JPasswordField();

        setResizable(false);
        setSize(new java.awt.Dimension(1410, 830));
        getContentPane().setLayout(null);

        pnAcc.setBackground(new java.awt.Color(245, 247, 250));
        pnAcc.setPreferredSize(new java.awt.Dimension(1180, 720));
        pnAcc.setLayout(null);

        pnInfo.setBackground(new java.awt.Color(153, 204, 255));
        pnInfo.setForeground(new java.awt.Color(255, 255, 255));
        pnInfo.setRequestFocusEnabled(false);
        pnInfo.setLayout(null);

        lbTitleInfo.setBackground(new java.awt.Color(102, 102, 102));
        lbTitleInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitleInfo.setForeground(new java.awt.Color(102, 102, 102));
        lbTitleInfo.setText("TÀI KHOẢN CÁ NHÂN");
        pnInfo.add(lbTitleInfo);
        lbTitleInfo.setBounds(10, 10, 230, 30);

        pnAcc.add(pnInfo);
        pnInfo.setBounds(10, 0, 1180, 50);

        pnMain.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.setForeground(new java.awt.Color(51, 51, 51));
        pnMain.setLayout(null);

        pnAccInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnAccInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jlabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel6.setText("Địa chỉ:");

        tfDiaChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel7.setText("Mã nhân viên:");

        jlabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel8.setText("Họ và tên:");

        jlabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel9.setText("Điện thoại liên lạc:");

        tfMa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfMa.setText("KH001");

        tfTen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfDienThoai.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel10.setText("Email:");

        jlabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel11.setText("Ngày vào làm");

        tfNgayVaoLam.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel12.setText("Chức vụ");

        cbbChucVu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel24.setText("Ngày sinh");

        tfNgaySinh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        btnIMGInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/NoneAvater.png"))); // NOI18N
        btnIMGInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel25.setText("Giới tính");

        tfGioiTinh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnAccInfoLayout = new javax.swing.GroupLayout(pnAccInfo);
        pnAccInfo.setLayout(pnAccInfoLayout);
        pnAccInfoLayout.setHorizontalGroup(
            pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAccInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnAccInfoLayout.createSequentialGroup()
                                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTen)
                                            .addComponent(tfMa))
                                        .addGap(27, 27, 27))
                                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                                        .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnIMGInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnAccInfoLayout.createSequentialGroup()
                                .addComponent(jlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAccInfoLayout.createSequentialGroup()
                                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                                        .addComponent(jlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNgayVaoLam))
                                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                                        .addComponent(jlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)))
                        .addGap(303, 303, 303))
                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnAccInfoLayout.createSequentialGroup()
                                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnAccInfoLayout.setVerticalGroup(
            pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAccInfoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAccInfoLayout.createSequentialGroup()
                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel7))
                        .addGap(16, 16, 16)
                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel8))
                        .addGap(36, 36, 36)
                        .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel12)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnIMGInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel24)
                    .addComponent(jlabel25))
                .addGap(22, 22, 22)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel9))
                .addGap(27, 27, 27)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel10))
                .addGap(24, 24, 24)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel6))
                .addGap(18, 18, 18)
                .addGroup(pnAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel11)
                    .addComponent(tfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        TablePane.addTab("Thông tin cá nhân", pnAccInfo);

        pnEditAccInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnEditAccInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jlabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel18.setText("Địa chỉ");

        tfAdress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel19.setText("Mã nhân viên");

        jlabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel20.setText("Họ và tên");

        jlabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel21.setText("Điện thoại liên lạc");

        tfID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfID.setText("KH001");
        tfID.setEnabled(false);

        tfName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfPhone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfEmailEdit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel22.setText("Email");

        jlabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel23.setText("Ngày sinh");

        btnSaveEdit.setBackground(new java.awt.Color(81, 141, 245));
        btnSaveEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSaveEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveEdit.setText("Lưu");
        btnSaveEdit.setBorder(null);
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        btnReloadEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReloadEdit.setForeground(new java.awt.Color(102, 102, 102));
        btnReloadEdit.setText("Làm mới");
        btnReloadEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReloadEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadEditActionPerformed(evt);
            }
        });

        jlabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel26.setText("Giới tính");

        cbbGender.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));
        cbbGender.setDoubleBuffered(true);

        dtpk.setBackground(new java.awt.Color(255, 255, 255));
        dtpk.setDateFormatString("dd/MM/yyyy");
        dtpk.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnEditAccInfoLayout = new javax.swing.GroupLayout(pnEditAccInfo);
        pnEditAccInfo.setLayout(pnEditAccInfoLayout);
        pnEditAccInfoLayout.setHorizontalGroup(
            pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEditAccInfoLayout.createSequentialGroup()
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReloadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPhone)
                                    .addComponent(tfEmailEdit)))
                            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName)
                                    .addComponent(tfID)))
                            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfAdress)))
                            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                                .addComponent(jlabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtpk, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)))))
                .addGap(287, 287, 287))
        );
        pnEditAccInfoLayout.setVerticalGroup(
            pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel19))
                .addGap(25, 25, 25)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel20)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                        .addComponent(jlabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dtpk, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                        .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlabel21)))
                        .addGap(52, 52, 52)
                        .addComponent(jlabel22))
                    .addGroup(pnEditAccInfoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(tfEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel18)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel26))
                .addGap(39, 39, 39)
                .addGroup(pnEditAccInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReloadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        TablePane.addTab("Chỉnh sửa thông tin", pnEditAccInfo);

        pnSecurity.setBackground(new java.awt.Color(255, 255, 255));
        pnSecurity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jlabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel13.setText("Mã nhân viên:");

        jlabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel15.setText("Mật khẩu mới");

        tfIDEditPass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfIDEditPass.setText("KH001");
        tfIDEditPass.setEnabled(false);

        jlabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel16.setText("Mật khẩu hiện tại");

        btnSavePass.setBackground(new java.awt.Color(81, 141, 245));
        btnSavePass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSavePass.setForeground(new java.awt.Color(255, 255, 255));
        btnSavePass.setText("Lưu");
        btnSavePass.setBorder(null);
        btnSavePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassActionPerformed(evt);
            }
        });

        btnReLoadPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReLoadPass.setForeground(new java.awt.Color(102, 102, 102));
        btnReLoadPass.setText("Làm mới");
        btnReLoadPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReLoadPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReLoadPassActionPerformed(evt);
            }
        });

        jlabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel17.setText("Xác nhận mật khẩu mới");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Đảm bảo rằng mật khẩu mới đủ mạnh và không chia sẻ với người khác.");

        tfConfirmPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tfNewPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tfOldPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnSecurityLayout = new javax.swing.GroupLayout(pnSecurity);
        pnSecurity.setLayout(pnSecurityLayout);
        pnSecurityLayout.setHorizontalGroup(
            pnSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSecurityLayout.createSequentialGroup()
                .addGroup(pnSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSecurityLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSecurityLayout.createSequentialGroup()
                        .addGap(830, 830, 830)
                        .addComponent(btnReLoadPass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSecurityLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIDEditPass)
                            .addComponent(jlabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                            .addComponent(tfNewPass)
                            .addComponent(tfOldPass))))
                .addContainerGap())
        );
        pnSecurityLayout.setVerticalGroup(
            pnSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSecurityLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIDEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jlabel16)
                .addGap(14, 14, 14)
                .addComponent(tfOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabel17)
                .addGap(18, 18, 18)
                .addComponent(tfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pnSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReLoadPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pnSecurityLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlabel15, jlabel17, tfConfirmPass, tfNewPass, tfOldPass});

        TablePane.addTab("Bảo mật tài khoản", pnSecurity);

        pnMain.add(TablePane);
        TablePane.setBounds(20, 20, 1420, 650);

        pnAcc.add(pnMain);
        pnMain.setBounds(0, 50, 1510, 740);

        getContentPane().add(pnAcc);
        pnAcc.setBounds(0, 0, 1180, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReLoadPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReLoadPassActionPerformed
        // TODO add your handling code here:
        tfOldPass.setText("");
        tfNewPass.setText("");
        tfConfirmPass.setText("");
    }//GEN-LAST:event_btnReLoadPassActionPerformed

    private void btnSavePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassActionPerformed
        // TODO add your handling code here:
        NhanVien nv = NV.getOne(ms.staffId);

        // Lấy chuỗi từ JPasswordField
        String oldPass = new String(tfOldPass.getPassword());
        String newPass = new String(tfNewPass.getPassword());
        String confirmPass = new String(tfConfirmPass.getPassword());

    if (!nv.getMatKhau().equals(oldPass)) {
        JOptionPane.showMessageDialog(null, "Mật khẩu cũ không đúng", "", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (newPass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Mật khẩu mới không được trống", "", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!newPass.equals(confirmPass)) {
        JOptionPane.showMessageDialog(null, "Mật khẩu mới và xác nhận mật khẩu cần giống nhau", "", JOptionPane.ERROR_MESSAGE);
        return;
    }

    NV.changePass(ms.staffId, newPass);
    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
        }//GEN-LAST:event_btnSavePassActionPerformed

    private boolean checkAge(JDateChooser d)
    {
        Date selectedDate = d.getDate();
        if (selectedDate == null) return false;
        LocalDate birthDate = selectedDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        LocalDate today = LocalDate.now();
        int age = Period.between(birthDate, today).getYears(); 
        return  age >= 18 && age<100  ;
    }
    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        // TODO add your handling code here:
        String name = tfName.getText().trim();
            if(name.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Tên không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(!checkAge(dtpk))
            {
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lê","",JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String NS = sdf.format(dtpk.getDate());
            String rePhone = "^(03|05|07|08|09)\\d{8}$";
            String phone = tfPhone.getText().trim();
            if (!phone.matches(rePhone)) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NV.checkPhone(phone,ms.staffId)!=0)
            {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String reEmail = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
            String email = tfEmail.getText().trim();
            if (!email.matches(reEmail)) {
                JOptionPane.showMessageDialog(null, "Email không đúng định dạng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NV.checkEmail(email,ms.staffId)!=0)
            {
                JOptionPane.showMessageDialog(null, "Địa chỉ email đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String addr = tfAdress.getText().trim();
            boolean gioitinh = true;
            if(cbbGender.getSelectedIndex() == 0) gioitinh=false;
            NhanVien n = new NhanVien();
            n.setChucVu(NV.getOne(ms.staffId).getChucVu());
            n.setDiaChi(addr) ;
            n.setSoDienThoai(phone);
            n.setEmail(email);
            n.setHoTen(name);
            n.setNgaySinh(NS);
            n.setGioiTinh(gioitinh);
            n.setMaNhanVien(ms.staffId);
            n.setAnh(NV.getOne(ms.staffId).getAnh());
            NV.update(n);
            JOptionPane.showMessageDialog(null, "Cập nhật thông tin thành công");
            loadAccountInfo();
    }//GEN-LAST:event_btnSaveEditActionPerformed

    private void btnReloadEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadEditActionPerformed
        // TODO add your handling code here:
        NhanVien nv = NV.getOne(ms.staffId);
        tfID.setText(nv.getMaNhanVien().toString());
        tfName.setText(nv.getHoTen());
        tfPhone.setText(nv.getSoDienThoai());
        tfEmailEdit.setText(nv.getEmail());
        tfAdress.setText(nv.getDiaChi());
    }//GEN-LAST:event_btnReloadEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountScreen(new mainScreen()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TablePane;
    private javax.swing.JButton btnIMGInfo;
    private javax.swing.JButton btnReLoadPass;
    private javax.swing.JButton btnReloadEdit;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JButton btnSavePass;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbGender;
    private com.toedter.calendar.JDateChooser dtpk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel jlabel13;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JLabel jlabel16;
    private javax.swing.JLabel jlabel17;
    private javax.swing.JLabel jlabel18;
    private javax.swing.JLabel jlabel19;
    private javax.swing.JLabel jlabel20;
    private javax.swing.JLabel jlabel21;
    private javax.swing.JLabel jlabel22;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JLabel jlabel24;
    private javax.swing.JLabel jlabel25;
    private javax.swing.JLabel jlabel26;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel lbTitleInfo;
    private javax.swing.JPanel pnAcc;
    private javax.swing.JPanel pnAccInfo;
    private javax.swing.JPanel pnEditAccInfo;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSecurity;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JPasswordField tfConfirmPass;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfDienThoai;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailEdit;
    private javax.swing.JTextField tfGioiTinh;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIDEditPass;
    private javax.swing.JTextField tfMa;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfNewPass;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfNgayVaoLam;
    private javax.swing.JPasswordField tfOldPass;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables

    private void loadScreen() {
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 830));
        setLocationRelativeTo(null);
        editButton();
        editCombobox();
        loadRoles();  
        editTabTitle(TablePane, pnAccInfo, "Thông tin cá nhân", 0);
        editTabTitle(TablePane, pnEditAccInfo, "Chỉnh sửa thông tin", 1);
        editTabTitle(TablePane, pnSecurity, "Bảo mật tài khoản", 2);
        
        loadAccountInfo();

    }

    private JButton setPropertiesButton(JButton b) {
        b.setForeground(new java.awt.Color(102, 102, 102));
        b.setContentAreaFilled(false);
        return b;
    }

    private void editButton() {
        btnReloadEdit.setBackground(Color.WHITE);
        btnReLoadPass.setContentAreaFilled(false);
        btnReloadEdit.setContentAreaFilled(false);
    }

    private void editCombobox() {
        cbbChucVu.setBackground(Color.WHITE);
    }

    private void editTabTitle(JTabbedPane tabbedPane, JPanel tabPanel, String title, int index) {
        JLabel label = new JLabel(title);
        label.setFont(new java.awt.Font("Arial", 0, 16));
        label.setPreferredSize(new Dimension(200, 30));
        tabbedPane.setTabComponentAt(index, label);
    }

    
}
