/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Eployee;

import DAO.HoaDonDAO;
import DAO.NhanVienDAO;
import custom.roundButton;
import GUI.Login.loginFrame;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import modal.NhanVien;

/**
 *
 * @author Minh
 */
public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public final int staffId;
    public int currentInvoiceId = -1;
    HoaDonDAO HD = new HoaDonDAO();
    public mainScreen(int staffId) {
        this.staffId = staffId;
        initComponents();
        setSize(new java.awt.Dimension(1400, 830));
        loadTime();
        loadAccountInfo();
        startClock();
        editButton(btnProduct);
        if(HD.selectAll_NonePaid().size()==0)
            HD.insert(staffId);
        openInternalFrame(btnProduct.getText().trim());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public mainScreen() {
        this(-1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        pnAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnControls = new javax.swing.JPanel();
        btnProduct = new javax.swing.JButton();
        btnHistosty_Paid = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnTitle = new javax.swing.JPanel();
        lbStoreName = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbIMG = new javax.swing.JLabel();
        pnChildScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setPreferredSize(new java.awt.Dimension(200, 790));
        pnMenu.setLayout(null);

        pnAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnAccount.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thu ngân : NV001");
        pnAccount.add(jLabel1);
        jLabel1.setBounds(16, 120, 160, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tăng Hữu Minh");
        pnAccount.add(jLabel2);
        jLabel2.setBounds(10, 145, 160, 20);

        pnMenu.add(pnAccount);
        pnAccount.setBounds(2, 5, 190, 180);

        pnControls.setBackground(new java.awt.Color(255, 255, 255));

        btnProduct.setBackground(new java.awt.Color(204, 255, 255));
        btnProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(0, 0, 153));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/box.png"))); // NOI18N
        btnProduct.setText("SẢN PHẨM        ");
        btnProduct.setBorder(null);
        btnProduct.setBorderPainted(false);
        btnProduct.setFocusPainted(false);
        btnProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProduct.setIconTextGap(8);
        btnProduct.setInheritsPopupMenu(true);
        btnProduct.setPreferredSize(new java.awt.Dimension(194, 55));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnProduct);

        btnHistosty_Paid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHistosty_Paid.setForeground(new java.awt.Color(102, 102, 102));
        btnHistosty_Paid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/document.png"))); // NOI18N
        btnHistosty_Paid.setText("LỊCH SỬ              ");
        btnHistosty_Paid.setToolTipText("");
        btnHistosty_Paid.setBorder(null);
        btnHistosty_Paid.setBorderPainted(false);
        btnHistosty_Paid.setDisabledIcon(null);
        btnHistosty_Paid.setFocusPainted(false);
        btnHistosty_Paid.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHistosty_Paid.setPreferredSize(new java.awt.Dimension(194, 55));
        btnHistosty_Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnHistosty_Paid);

        btnClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClient.setForeground(new java.awt.Color(102, 102, 102));
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/friends.png"))); // NOI18N
        btnClient.setText("KHÁCH HÀNG ");
        btnClient.setBorder(null);
        btnClient.setBorderPainted(false);
        btnClient.setDisabledIcon(null);
        btnClient.setFocusPainted(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClient.setPreferredSize(new java.awt.Dimension(194, 55));
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnClient);

        btnAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(102, 102, 102));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/user.png"))); // NOI18N
        btnAccount.setText("TÀI KHOẢN      ");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.setDisabledIcon(null);
        btnAccount.setFocusPainted(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAccount.setPreferredSize(new java.awt.Dimension(194, 55));
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnAccount);

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 102, 102));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/loupe.png"))); // NOI18N
        btnSearch.setText("TÌM KIẾM        ");
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setDisabledIcon(null);
        btnSearch.setFocusPainted(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSearch.setPreferredSize(new java.awt.Dimension(194, 55));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnSearch);

        btnLogout.setBackground(new java.awt.Color(255, 82, 82));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/logout.png"))); // NOI18N
        btnLogout.setText("ĐĂNG XUẤT");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setDisabledIcon(null);
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setPreferredSize(new java.awt.Dimension(194, 55));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnControls.add(btnLogout);

        pnMenu.add(pnControls);
        pnControls.setBounds(0, 180, 190, 470);

        pnTitle.setBackground(new java.awt.Color(71, 139, 250));
        pnTitle.setRequestFocusEnabled(false);
        pnTitle.setLayout(null);

        lbStoreName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbStoreName.setForeground(new java.awt.Color(255, 255, 255));
        lbStoreName.setText("HỆ THỐNG QUẢN LÝ SIÊU THỊ KMT");
        pnTitle.add(lbStoreName);
        lbStoreName.setBounds(50, 10, 340, 30);

        lbTime.setBackground(new java.awt.Color(0, 0, 0));
        lbTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 255, 255));
        lbTime.setText("jLabel2");
        pnTitle.add(lbTime);
        lbTime.setBounds(1220, 10, 160, 30);

        lbIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/menu-button.png"))); // NOI18N
        lbIMG.setText("jLabel1");
        pnTitle.add(lbIMG);
        lbIMG.setBounds(10, 10, 40, 30);

        pnChildScreen.setBackground(new java.awt.Color(245, 247, 250));

        javax.swing.GroupLayout pnChildScreenLayout = new javax.swing.GroupLayout(pnChildScreen);
        pnChildScreen.setLayout(pnChildScreenLayout);
        pnChildScreenLayout.setHorizontalGroup(
            pnChildScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        pnChildScreenLayout.setVerticalGroup(
            pnChildScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnChildScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnChildScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new loginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:\
        String text = ((JButton) evt.getSource()).getText().trim();
        editButton((JButton) evt.getSource());
        openInternalFrame(text);
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnHistosty_Paid;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbIMG;
    private javax.swing.JLabel lbStoreName;
    private javax.swing.JLabel lbTime;
    private javax.swing.JPanel pnAccount;
    private javax.swing.JPanel pnChildScreen;
    private javax.swing.JPanel pnControls;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables

    public void openInternalFrame(String key) {
        pnChildScreen.removeAll();
        pnChildScreen.setLayout(new BorderLayout());

        switch (key) {
            case "SẢN PHẨM": {
                productScreen ps = new productScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "KHÁCH HÀNG": {
                clientScreen ps = new clientScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "TÀI KHOẢN": {
                accountScreen ps = new accountScreen(this);

                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "LỊCH SỬ": {
                historyScreen ps = new historyScreen();
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "TÌM KIẾM": {
                searchScreen ps = new searchScreen();
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "THANH TOÁN": {
                int invId = this.currentInvoiceId;
                int sId = this.staffId;
                if (invId < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng tạo hoặc chọn hóa đơn trước.", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    break;
                }
                paidScreen ps = new paidScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
        }
        pnChildScreen.revalidate();
        pnChildScreen.repaint();
    }

    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadTime();
            }
        });
        timer.start();
    }

    private void loadTime() {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        lbTime.setText(now.format(formatter));
    }

    private JButton setPropertiesButton(JButton b) {
        b.setForeground(new java.awt.Color(102, 102, 102));
        b.setContentAreaFilled(false);
        return b;
    }

    private void editButton(JButton b) {
        btnProduct = setPropertiesButton(btnProduct);
        btnClient = setPropertiesButton(btnClient);
        btnHistosty_Paid = setPropertiesButton(btnHistosty_Paid);
        btnAccount = setPropertiesButton(btnAccount);
        btnSearch = setPropertiesButton(btnSearch);
        b.setBackground(new java.awt.Color(204, 255, 255));
        b.setForeground(new java.awt.Color(0, 0, 153));
        b.setContentAreaFilled(true);
    }

    private void loadAccountInfo() {
        jLabel1.setText(String.format("Thu ngân: NV%03d", staffId));
        NhanVienDAO nv = new NhanVienDAO();
        NhanVien n = nv.getOne(staffId);
        String acc = n.getHoTen();
        jLabel2.setText(acc.trim());
        roundButton button = new roundButton("");
        button.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
//        if(n.getAnh()!=null)
//        {
//            URL imageUrl = getClass().getResource(n.getAnh());
//            ImageIcon icon = new ImageIcon(imageUrl);
//            Image i = icon.getImage().getScaledInstance(120, 170, Image.SCALE_SMOOTH);
//            button.setIcon(new ImageIcon(i));
//        }
//        else button.setIcon(new ImageIcon("src/resources/employee/NoneAvater - Copy.png"));
 button.setIcon(new ImageIcon("src/resources/employee/NoneAvater - Copy.png"));
        button.setBounds(40, 5, 110, 110);
        pnAccount.add(button);
    }
}
