/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Admin;

import DAO.ChiTietHoaDonDAO;
import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import modal.ChiTietHoaDon;
import modal.HoaDon;
import modal.KhachHang;

/**
 *
 * @author Minh
 */
public class detailBill_AdminScreen extends javax.swing.JFrame {

    mainAdminScreen ms;
    int idBill;
    double sumPrice;
    double discount;
    HoaDonDAO HD = new HoaDonDAO();
    KhachHangDAO KH = new KhachHangDAO();
    NhanVienDAO NV = new NhanVienDAO();
    /** Creates new form productFrame */
    public detailBill_AdminScreen(mainAdminScreen m,int idB) {
        ms = m;
        idBill = idB;
        initComponents();
        loadScreen();
        loadDetailBill();
        loadStaffInfo();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnDetailBill = new javax.swing.JPanel();
        pnDetailBill1 = new javax.swing.JPanel();
        ScrollTable = new javax.swing.JScrollPane();
        tableBill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbSumPrice = new javax.swing.JLabel();
        pnTotal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbTotalPrice = new javax.swing.JLabel();
        pnInfo = new javax.swing.JPanel();
        lbTitleList_client = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        lbIDStaff = new javax.swing.JLabel();
        lbNameStaff = new javax.swing.JLabel();
        lbIDClient = new javax.swing.JLabel();
        lbTitleList_client1 = new javax.swing.JLabel();
        lbNameClient = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        lbNowPoint = new javax.swing.JLabel();
        lbNewPoint = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        lbTitleList_client2 = new javax.swing.JLabel();
        jlabel10 = new javax.swing.JLabel();
        lbDateTimePaid = new javax.swing.JLabel();
        pnCRUD = new javax.swing.JPanel();
        lb_btnDetailBill = new javax.swing.JLabel();
        lb_btnBill = new javax.swing.JLabel();
        btnPrintDetail = new javax.swing.JButton();

        setResizable(false);
        setSize(new java.awt.Dimension(1180, 720));
        getContentPane().setLayout(null);

        pnMain.setBackground(new java.awt.Color(245, 247, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1180, 720));
        pnMain.setLayout(null);

        pnDetailBill.setBackground(new java.awt.Color(255, 255, 255));

        pnDetailBill1.setBackground(new java.awt.Color(249, 250, 251));

        tableBill.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sản phẩm", "Giá bán", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBill.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableBill.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableBill.setFillsViewportHeight(true);
        tableBill.setGridColor(new java.awt.Color(0, 0, 0));
        tableBill.setMinimumSize(new java.awt.Dimension(60, 75));
        tableBill.setPreferredSize(new java.awt.Dimension(298, 75));
        tableBill.setRowHeight(40);
        tableBill.setShowGrid(true);
        tableBill.setShowHorizontalLines(false);
        ScrollTable.setViewportView(tableBill);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Giảm giá:");

        lbDiscount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(204, 0, 0));
        lbDiscount.setText("0.000đ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Tổng cộng:");

        lbSumPrice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbSumPrice.setText("100.000đ");

        pnTotal.setBackground(new java.awt.Color(239, 246, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Thành tiền:");

        lbTotalPrice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbTotalPrice.setText("90.000đ");

        javax.swing.GroupLayout pnTotalLayout = new javax.swing.GroupLayout(pnTotal);
        pnTotal.setLayout(pnTotalLayout);
        pnTotalLayout.setHorizontalGroup(
            pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84)
                .addComponent(lbTotalPrice)
                .addGap(24, 24, 24))
        );
        pnTotalLayout.setVerticalGroup(
            pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTotalLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalPrice)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnDetailBill1Layout = new javax.swing.GroupLayout(pnDetailBill1);
        pnDetailBill1.setLayout(pnDetailBill1Layout);
        pnDetailBill1Layout.setHorizontalGroup(
            pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailBill1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailBill1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86)
                        .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSumPrice)
                            .addComponent(lbDiscount))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailBill1Layout.createSequentialGroup()
                        .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(pnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnDetailBill1Layout.setVerticalGroup(
            pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailBill1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbSumPrice))
                .addGap(18, 18, 18)
                .addGroup(pnDetailBill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbDiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnInfo.setBackground(new java.awt.Color(255, 255, 255));

        lbTitleList_client.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitleList_client.setForeground(new java.awt.Color(40, 93, 179));
        lbTitleList_client.setText("THÔNG TIN NHÂN VIÊN");

        jlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(153, 0, 0));
        jlabel1.setText("Hóa đơn có giá trị đổi trả trong cùng ngày");

        jlabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel2.setText("Mã nhân viên:");

        jlabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel3.setText("Họ tên nhân viên thanh toán:");

        jlabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel4.setText("140 Lê Trọng Tấn, P.Hòa Thạnh, Q.Tân Phú, Tp.Hồ Chí Minh");

        lbIDStaff.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbIDStaff.setText("1");

        lbNameStaff.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNameStaff.setText("Minh");

        lbIDClient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbIDClient.setText("1");

        lbTitleList_client1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitleList_client1.setForeground(new java.awt.Color(40, 93, 179));
        lbTitleList_client1.setText("THÔNG TIN KHÁCH HÀNG");

        lbNameClient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNameClient.setText("Minh");

        jlabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel6.setText("Mã khách hàng:");

        jlabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel7.setText("Họ tên khách hàng:");

        lbNowPoint.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNowPoint.setText("1");

        lbNewPoint.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNewPoint.setText("1");

        jlabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel8.setText("Điểm tích lũy đang có:");

        jlabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel9.setText("Điểm quy đổi từ thanh toán:");

        lbTitleList_client2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitleList_client2.setForeground(new java.awt.Color(40, 93, 179));
        lbTitleList_client2.setText("THÔNG TIN KHÁC");

        jlabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel10.setText("Thời gian thanh toán:");

        lbDateTimePaid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbDateTimePaid.setText("1");

        javax.swing.GroupLayout pnInfoLayout = new javax.swing.GroupLayout(pnInfo);
        pnInfo.setLayout(pnInfoLayout);
        pnInfoLayout.setHorizontalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInfoLayout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInfoLayout.createSequentialGroup()
                        .addComponent(jlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInfoLayout.createSequentialGroup()
                        .addComponent(jlabel1)
                        .addGap(142, 142, 142))))
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitleList_client1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnInfoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNewPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNowPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(lbIDClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNameStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbIDStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDateTimePaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitleList_client2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTitleList_client, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnInfoLayout.setVerticalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTitleList_client, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addComponent(jlabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnInfoLayout.createSequentialGroup()
                        .addComponent(lbIDStaff)
                        .addGap(18, 18, 18)
                        .addComponent(lbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbTitleList_client1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel6)
                    .addComponent(lbIDClient))
                .addGap(18, 18, 18)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel8)
                    .addComponent(lbNowPoint))
                .addGap(18, 18, 18)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNewPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbTitleList_client2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel10)
                    .addComponent(lbDateTimePaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel1)
                .addGap(18, 18, 18)
                .addComponent(jlabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnDetailBillLayout = new javax.swing.GroupLayout(pnDetailBill);
        pnDetailBill.setLayout(pnDetailBillLayout);
        pnDetailBillLayout.setHorizontalGroup(
            pnDetailBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDetailBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDetailBillLayout.setVerticalGroup(
            pnDetailBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailBillLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnDetailBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnDetailBill1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnMain.add(pnDetailBill);
        pnDetailBill.setBounds(0, 50, 1170, 650);

        pnCRUD.setBackground(new java.awt.Color(255, 255, 255));
        pnCRUD.setForeground(new java.awt.Color(51, 51, 51));
        pnCRUD.setLayout(null);

        lb_btnDetailBill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_btnDetailBill.setForeground(new java.awt.Color(153, 0, 153));
        lb_btnDetailBill.setText("> THÔNG TIN CHI TIẾT");
        pnCRUD.add(lb_btnDetailBill);
        lb_btnDetailBill.setBounds(120, 8, 220, 22);

        lb_btnBill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_btnBill.setForeground(new java.awt.Color(153, 0, 153));
        lb_btnBill.setText("HÓA ĐƠN");
        lb_btnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_btnBillMouseClicked(evt);
            }
        });
        pnCRUD.add(lb_btnBill);
        lb_btnBill.setBounds(10, 8, 100, 22);

        btnPrintDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/printer.png"))); // NOI18N
        btnPrintDetail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));
        btnPrintDetail.setBorderPainted(false);
        btnPrintDetail.setFocusPainted(false);
        btnPrintDetail.setFocusable(false);
        pnCRUD.add(btnPrintDetail);
        btnPrintDetail.setBounds(1130, 0, 40, 40);

        pnMain.add(pnCRUD);
        pnCRUD.setBounds(0, 0, 1170, 40);

        getContentPane().add(pnMain);
        pnMain.setBounds(0, 0, 1180, 710);
        pnMain.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_btnBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_btnBillMouseClicked
        // TODO add your handling code here:
        ms.openInternalFrame("HÓA ĐƠN");
    }//GEN-LAST:event_lb_btnBillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailBill_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailBill_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailBill_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailBill_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailBill_AdminScreen(new mainAdminScreen(),1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollTable;
    private javax.swing.JButton btnPrintDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel lbDateTimePaid;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbIDClient;
    private javax.swing.JLabel lbIDStaff;
    private javax.swing.JLabel lbNameClient;
    private javax.swing.JLabel lbNameStaff;
    private javax.swing.JLabel lbNewPoint;
    private javax.swing.JLabel lbNowPoint;
    private javax.swing.JLabel lbSumPrice;
    private javax.swing.JLabel lbTitleList_client;
    private javax.swing.JLabel lbTitleList_client1;
    private javax.swing.JLabel lbTitleList_client2;
    private javax.swing.JLabel lbTotalPrice;
    private javax.swing.JLabel lb_btnBill;
    private javax.swing.JLabel lb_btnDetailBill;
    private javax.swing.JPanel pnCRUD;
    private javax.swing.JPanel pnDetailBill;
    private javax.swing.JPanel pnDetailBill1;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTotal;
    private javax.swing.JTable tableBill;
    // End of variables declaration//GEN-END:variables

    
    private void loadScreen()
    {
        setLocationRelativeTo(null);
        editTable();
        loadCustomerInfo();
        loadStaffInfo();
        loadDetailBill();
        JOptionPane.showMessageDialog(null,"Tải dữ liệu thành công","",JOptionPane.INFORMATION_MESSAGE);
    }
    private void editTable()
    {
         JTableHeader header = tableBill.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 14));
        header.setBackground(Color.LIGHT_GRAY);
        header.setForeground(Color.BLACK);
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) tableBill.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        Object[][] data = {};
        Object[] columnNames = {"Sản phẩm","Giá bán", "Số lượng","Thành tiền"};
        TableModel model = new DefaultTableModel(data, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.tableBill.setModel(model);
    }
    private void loadDetailBill() {
        
        DefaultTableModel model = (DefaultTableModel) tableBill.getModel();
        model.setRowCount(0);
        sumPrice = 0;
        ChiTietHoaDonDAO ct =new ChiTietHoaDonDAO();
        List<ChiTietHoaDon> list = ct.findByMaHoaDon(ms.billID);
        for(ChiTietHoaDon x : list)
        {
            String name = new SanPhamDAO().findById(x.getMaSanPham()).getTenSanPham();
            double price = x.getGia();
            int qty = x.getSoLuong();
            double tot = x.getGia()*x.getSoLuong();
            sumPrice += tot;
            
            model.addRow(new Object[]{name, price, qty, tot});
        }
        lbSumPrice.setText(String.format("%,.0f₫", sumPrice));
        lbTotalPrice.setText(String.format("%,.0f₫", (sumPrice)));
    }

    private void loadStaffInfo() {
        HoaDon h= HD.findById(ms.billID);
        lbIDStaff.setText(h.getMaNhanVien().toString());
        lbNameStaff.setText(NV.getnameByID(h.getMaHoaDon()));
        lbDateTimePaid.setText(h.getNgayLap().toString().split("T")[0]+"   "+h.getNgayLap().toString().split("T")[1]);
    }

    private void loadCustomerInfo()
    {
        HoaDon h= HD.findById(ms.billID);
        if(h.getTrangThai().equals("Mua sắm"))
        {
            lbIDClient.setText("Trống");
            lbNameClient.setText("Trống");
            lbNowPoint.setText("0");
            lbNewPoint.setText("0");
            lbDiscount.setText(String.format("%,.0f₫",discount));
            lbSumPrice.setText(String.format("%,.0f₫",sumPrice));
            return;
        }
        KhachHang k = KH.findById(h.getMaKhachHang());
        lbIDClient.setText(k.getMaKhachHang().toString());
        lbNameClient.setText(k.getHoTen());
        lbNowPoint.setText(k.getDiemTichLuy().toString());
        int s = (int)sumPrice / 100;
        lbNewPoint.setText(String.valueOf(s));
    }
}
