/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Admin;
import DAO.NhanVienDAO;
import GUI.Login.loginFrame;
import java.awt.BorderLayout;
import javax.swing.JButton;

import javax.swing.JPanel;

/**
 *
 * @author Minh
 */
public class mainAdminScreen extends javax.swing.JFrame {

    /** Creates new form main */
    public int staffId;
    public NhanVienDAO NV = new NhanVienDAO();
    public  int productID;
    public  int status;
    public int billID;
    public mainAdminScreen(int staffId) {
        this.staffId = staffId;
        initComponents();
        setLocationRelativeTo(null);
        editButton(btnChart);
        btnAdminIcon.setContentAreaFilled(false);
        // load tên user
        String staffName = loadStaffName(staffId);
        lbNameAdmin2.setText("Quản lý: " + staffName);

        openInternalFrame("THỐNG KÊ");
    }
    
    public mainAdminScreen() {
        setLocationRelativeTo(null);
        initComponents();
        setSize(new java.awt.Dimension(1400, 830));
        editButton(btnChart);
        btnAdminIcon.setContentAreaFilled(false);
        openInternalFrame("THỐNG KÊ");
    }
    
    
    private String loadStaffName(int staffId) {
        return NV.getnameByID(staffId);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnControls = new javax.swing.JPanel();
        btnChart = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnOder = new javax.swing.JButton();
        btnHistosty_Paid = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnChildScreen = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbHiQuery2 = new javax.swing.JLabel();
        lbNameAdmin2 = new javax.swing.JLabel();
        btnAdminIcon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SIÊU THỊ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("KMT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pnControls.setBackground(new java.awt.Color(255, 255, 255));

        btnChart.setBackground(new java.awt.Color(204, 204, 255));
        btnChart.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/line-chart.png"))); // NOI18N
        btnChart.setText("THỐNG KÊ         ");
        btnChart.setBorder(null);
        btnChart.setBorderPainted(false);
        btnChart.setFocusPainted(false);
        btnChart.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChart.setPreferredSize(new java.awt.Dimension(194, 55));
        btnChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnChart);

        btnProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(102, 102, 102));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/box.png"))); // NOI18N
        btnProduct.setText("SẢN PHẨM        ");
        btnProduct.setBorder(null);
        btnProduct.setBorderPainted(false);
        btnProduct.setFocusPainted(false);
        btnProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProduct.setIconTextGap(8);
        btnProduct.setInheritsPopupMenu(true);
        btnProduct.setPreferredSize(new java.awt.Dimension(194, 55));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnProduct);

        btnEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(102, 102, 102));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/customer.png"))); // NOI18N
        btnEmployee.setText("NHÂN VIÊN         ");
        btnEmployee.setBorder(null);
        btnEmployee.setBorderPainted(false);
        btnEmployee.setFocusPainted(false);
        btnEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEmployee.setPreferredSize(new java.awt.Dimension(194, 55));
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnEmployee);

        btnClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClient.setForeground(new java.awt.Color(102, 102, 102));
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/friends.png"))); // NOI18N
        btnClient.setText("KHÁCH HÀNG ");
        btnClient.setBorder(null);
        btnClient.setBorderPainted(false);
        btnClient.setFocusPainted(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClient.setPreferredSize(new java.awt.Dimension(194, 55));
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnClient);

        btnAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(102, 102, 102));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/user.png"))); // NOI18N
        btnAccount.setText("TÀI KHOẢN      ");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.setFocusPainted(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAccount.setPreferredSize(new java.awt.Dimension(194, 55));
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnAccount);

        btnSupplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(102, 102, 102));
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/deal.png"))); // NOI18N
        btnSupplier.setText("NHÀ CUNG CẤP");
        btnSupplier.setBorder(null);
        btnSupplier.setBorderPainted(false);
        btnSupplier.setFocusPainted(false);
        btnSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSupplier.setPreferredSize(new java.awt.Dimension(194, 55));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnSupplier);

        btnOder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOder.setForeground(new java.awt.Color(102, 102, 102));
        btnOder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/oder.png"))); // NOI18N
        btnOder.setText("NHẬP HÀNG      ");
        btnOder.setBorder(null);
        btnOder.setBorderPainted(false);
        btnOder.setFocusPainted(false);
        btnOder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnOder.setPreferredSize(new java.awt.Dimension(194, 55));
        btnOder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnOder);

        btnHistosty_Paid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHistosty_Paid.setForeground(new java.awt.Color(102, 102, 102));
        btnHistosty_Paid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/document.png"))); // NOI18N
        btnHistosty_Paid.setText("HÓA ĐƠN           ");
        btnHistosty_Paid.setToolTipText("");
        btnHistosty_Paid.setBorder(null);
        btnHistosty_Paid.setBorderPainted(false);
        btnHistosty_Paid.setFocusPainted(false);
        btnHistosty_Paid.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHistosty_Paid.setPreferredSize(new java.awt.Dimension(194, 55));
        btnHistosty_Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        pnControls.add(btnHistosty_Paid);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/logout_black.png"))); // NOI18N
        btnLogout.setText("ĐĂNG XUẤT       ");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setPreferredSize(new java.awt.Dimension(194, 55));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnControls, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnControls, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnChildScreen.setBackground(new java.awt.Color(245, 247, 250));

        javax.swing.GroupLayout pnChildScreenLayout = new javax.swing.GroupLayout(pnChildScreen);
        pnChildScreen.setLayout(pnChildScreenLayout);
        pnChildScreenLayout.setHorizontalGroup(
            pnChildScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1202, Short.MAX_VALUE)
        );
        pnChildScreenLayout.setVerticalGroup(
            pnChildScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbHiQuery2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbHiQuery2.setText("Xin chào buổi chiều!");

        lbNameAdmin2.setBackground(new java.awt.Color(0, 0, 0));
        lbNameAdmin2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbNameAdmin2.setText("Quản lý : ");

        btnAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/user.png"))); // NOI18N
        btnAdminIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));
        btnAdminIcon.setBorderPainted(false);
        btnAdminIcon.setFocusPainted(false);
        btnAdminIcon.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbHiQuery2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHiQuery2)
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdminIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNameAdmin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnChildScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnChildScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new loginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        String text = ((JButton) evt.getSource()).getText().trim();
        editButton((JButton) evt.getSource());
        openInternalFrame(text);
    }//GEN-LAST:event_btnActionPerformed

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainAdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainAdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainAdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainAdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainAdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnAdminIcon;
    private javax.swing.JButton btnChart;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnHistosty_Paid;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOder;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbHiQuery2;
    private javax.swing.JLabel lbNameAdmin2;
    private javax.swing.JPanel pnChildScreen;
    private javax.swing.JPanel pnControls;
    private javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables


    private JButton setPropertiesButton(JButton b) {
        b.setForeground(new java.awt.Color(102, 102, 102));
        b.setContentAreaFilled(false);
        return b;
    }

    private void editButton(JButton b) {
        btnChart = setPropertiesButton(btnChart);
        btnProduct = setPropertiesButton(btnProduct);
        btnEmployee = setPropertiesButton(btnEmployee);
        btnClient = setPropertiesButton(btnClient);
        btnHistosty_Paid = setPropertiesButton(btnHistosty_Paid);
        btnAccount = setPropertiesButton(btnAccount);
        btnSupplier = setPropertiesButton(btnSupplier);
        btnLogout = setPropertiesButton(btnLogout);
        btnOder = setPropertiesButton(btnOder);
        b.setBackground(new java.awt.Color(204, 204, 255));
        b.setForeground(new java.awt.Color(0, 0, 0));
        b.setContentAreaFilled(true);
    }
    
     public void openInternalFrame(String key) {
        pnChildScreen.removeAll();
        pnChildScreen.setLayout(new BorderLayout());
        switch (key) {
            case "THỐNG KÊ": {
                chart_AdminScreen ps = new chart_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "SẢN PHẨM": {
                product_AdminScreen ps = new product_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
           
            case "NHÂN VIÊN": {
                employee_AdminScreen ps = new employee_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
           
            case "KHÁCH HÀNG": {
                customer_AdminScreen ps = new customer_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "HÓA ĐƠN": {
                bill_AdminScreen ps = new bill_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            
            case "CHI TIẾT HÓA ĐƠN": {
                detailBill_AdminScreen ps = new detailBill_AdminScreen(this,productID);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "TÀI KHOẢN": {
                account_AdminScreen ps = new account_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "NHẬP HÀNG": {
                oder_AdminScreen ps = new oder_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
            case "NHÀ CUNG CẤP": {
                supplier_AdminScreen ps = new supplier_AdminScreen(this);
                JPanel panel = (JPanel) ps.getContentPane();
                panel.setPreferredSize(pnChildScreen.getSize());
                pnChildScreen.add(panel, BorderLayout.CENTER);
                break;
            }
        }

        pnChildScreen.revalidate();
        pnChildScreen.repaint();
    }
}
