/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Admin;

import DAO.NhaCungCapDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modal.NhaCungCap;

/**
 *
 * @author Minh
 */
public class supplier_AdminScreen extends javax.swing.JFrame {


    private DefaultTableModel model;
    private mainAdminScreen ms;
    private NhaCungCapDAO NCC = new NhaCungCapDAO();

    /**
     * Creates new form productFrame
     */
    public supplier_AdminScreen(mainAdminScreen m) {
        initComponents();
        loadScreen();
        setSize(new Dimension(1180, 720));
        this.ms = m;
        loadSuppliers();
    }

    private void loadSuppliers() {
        model.setRowCount(0);
        String text = " where tenNcc like N'%"+tfSeacrh.getText()+"%' ";
        String order = "order by maNhaCungCap asc";
        if(cbbSort.getSelectedIndex()==1) order = "order by tenNcc asc";
        else if(cbbSort.getSelectedIndex()==2) order = "order by trangthai asc";
       List<NhaCungCap> list = NCC.getAll_condition(text+order);
       for(NhaCungCap x : list)
       {
           model.addRow(new Object[]{x.getMaNhaCungCap(),x.getTenNcc(),x.getEmail(),x.getSoDienThoai(),x.getDiaChi(),x.getTrangThai()});
       }
        tableSupllier.setModel(model);
    }
    
    private void reloadForm() {
        if(cbbIDEdit.getSelectedIndex()<0) return;
        int id = Integer.parseInt(cbbIDEdit.getSelectedItem().toString());
        NhaCungCap ncc = NCC.findById(id);
            cbbIDEdit.setSelectedItem(String.valueOf(ncc.getMaNhaCungCap()));
            tfEmailEdit.setText(ncc.getTenNcc());
            tfAdressEdit.setText(ncc.getDiaChi());
            tfPhoneEdit.setText(ncc.getSoDienThoai());
            tfEmailEdit.setText(ncc.getEmail());
            cbbStatusEdit.setSelectedItem(ncc.getTrangThai());
            tfNameEdit.setText(ncc.getTenNcc());
        }
    private void clearForm() {
        tfIDAdd.setText(String.valueOf(NCC.getNewID()));
        tfNameAdd.setText("");
        tfAdressAdd.setText("");
        tfPhoneAdd.setText("");
        tfEmailAdd.setText("");}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnCRUD = new javax.swing.JPanel();
        lbTitleList_client = new javax.swing.JLabel();
        btnExportFIle = new javax.swing.JButton();
        pnCategori = new javax.swing.JPanel();
        TablePane = new javax.swing.JTabbedPane();
        pnSupplier = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        tableSupllier = new javax.swing.JTable();
        cbbSort = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tfSeacrh = new javax.swing.JTextField();
        btnDecor = new javax.swing.JButton();
        pnCreateSupplier = new javax.swing.JPanel();
        jlabel23 = new javax.swing.JLabel();
        tfAdressAdd = new javax.swing.JTextField();
        jlabel25 = new javax.swing.JLabel();
        jlabel26 = new javax.swing.JLabel();
        jlabel27 = new javax.swing.JLabel();
        tfIDAdd = new javax.swing.JTextField();
        tfNameAdd = new javax.swing.JTextField();
        tfPhoneAdd = new javax.swing.JTextField();
        tfEmailAdd = new javax.swing.JTextField();
        jlabel28 = new javax.swing.JLabel();
        btnSaveAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnEditSupplier = new javax.swing.JPanel();
        jlabel18 = new javax.swing.JLabel();
        tfAdressEdit = new javax.swing.JTextField();
        jlabel19 = new javax.swing.JLabel();
        jlabel20 = new javax.swing.JLabel();
        jlabel21 = new javax.swing.JLabel();
        tfNameEdit = new javax.swing.JTextField();
        tfPhoneEdit = new javax.swing.JTextField();
        tfEmailEdit = new javax.swing.JTextField();
        jlabel22 = new javax.swing.JLabel();
        btnSaveEdit = new javax.swing.JButton();
        jlabel24 = new javax.swing.JLabel();
        cbbStatusEdit = new javax.swing.JComboBox<>();
        cbbIDEdit = new javax.swing.JComboBox<>();
        btnClearEdit = new javax.swing.JButton();

        setResizable(false);
        setSize(new java.awt.Dimension(1400, 830));
        getContentPane().setLayout(null);

        pnMain.setBackground(new java.awt.Color(245, 247, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1180, 720));
        pnMain.setLayout(null);

        pnCRUD.setBackground(new java.awt.Color(255, 255, 255));
        pnCRUD.setForeground(new java.awt.Color(51, 51, 51));
        pnCRUD.setLayout(null);

        lbTitleList_client.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitleList_client.setForeground(new java.awt.Color(153, 0, 153));
        lbTitleList_client.setText("NHÀ CUNG CẤP");
        pnCRUD.add(lbTitleList_client);
        lbTitleList_client.setBounds(10, 8, 150, 22);

        btnExportFIle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExportFIle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/file-import.png"))); // NOI18N
        btnExportFIle.setText("Xuất file");
        btnExportFIle.setBorder(null);
        pnCRUD.add(btnExportFIle);
        btnExportFIle.setBounds(1030, 4, 130, 30);

        pnMain.add(pnCRUD);
        pnCRUD.setBounds(0, 0, 1180, 40);

        pnCategori.setBackground(new java.awt.Color(255, 255, 255));
        pnCategori.setForeground(new java.awt.Color(51, 51, 51));
        pnCategori.setLayout(null);

        pnSupplier.setBackground(new java.awt.Color(255, 255, 255));
        pnSupplier.setLayout(null);

        tableSupllier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tableSupllier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tableSupllier.setRowHeight(40);
        tableSupllier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScrollPane.setViewportView(tableSupllier);

        pnSupplier.add(ScrollPane);
        ScrollPane.setBounds(10, 60, 1150, 530);

        cbbSort.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhà cung cấp", "Tên nhà cung cấp", "Trạng thái" }));
        pnSupplier.add(cbbSort);
        cbbSort.setBounds(1000, 10, 160, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Sắp xếp theo");
        pnSupplier.add(jLabel1);
        jLabel1.setBounds(910, 10, 80, 30);

        tfSeacrh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfSeacrh.setVerifyInputWhenFocusTarget(false);
        tfSeacrh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSeacrhActionPerformed(evt);
            }
        });
        pnSupplier.add(tfSeacrh);
        tfSeacrh.setBounds(290, 10, 560, 30);

        btnDecor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDecor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee/filters.png"))); // NOI18N
        btnDecor.setText("Tất cả");
        btnDecor.setBorder(null);
        btnDecor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnSupplier.add(btnDecor);
        btnDecor.setBounds(10, 10, 70, 20);

        TablePane.addTab("Danh sách Nhà cung cấp", pnSupplier);

        pnCreateSupplier.setBackground(new java.awt.Color(255, 255, 255));
        pnCreateSupplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jlabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel23.setText("Địa chỉ");

        tfAdressAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel25.setText("Mã nhà cung cấp");

        jlabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel26.setText("Tên nhà cung cấp");

        jlabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel27.setText("Điện thoại liên lạc");

        tfIDAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tfIDAdd.setText("KH001");

        tfNameAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfPhoneAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfEmailAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel28.setText("Email");

        btnSaveAdd.setBackground(new java.awt.Color(81, 141, 245));
        btnSaveAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSaveAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAdd.setText("Lưu");
        btnSaveAdd.setBorder(null);
        btnSaveAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(102, 102, 102));
        btnClear.setText("Làm mới");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCreateSupplierLayout = new javax.swing.GroupLayout(pnCreateSupplier);
        pnCreateSupplier.setLayout(pnCreateSupplierLayout);
        pnCreateSupplierLayout.setHorizontalGroup(
            pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCreateSupplierLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfEmailAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPhoneAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfAdressAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCreateSupplierLayout.createSequentialGroup()
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSaveAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfIDAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                        .addComponent(jlabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNameAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)))
                .addGap(158, 158, 158))
        );
        pnCreateSupplierLayout.setVerticalGroup(
            pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCreateSupplierLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlabel25)
                .addGap(8, 8, 8)
                .addComponent(tfIDAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPhoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdressAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(pnCreateSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TablePane.addTab("Thêm nhà cung cấp", pnCreateSupplier);

        pnEditSupplier.setBackground(new java.awt.Color(255, 255, 255));
        pnEditSupplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jlabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel18.setText("Địa chỉ");

        tfAdressEdit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel19.setText("Mã nhà cung cấp");

        jlabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel20.setText("Tên nhà cung cấp");

        jlabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel21.setText("Điện thoại liên lạc");

        tfNameEdit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfPhoneEdit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tfEmailEdit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel22.setText("Email");

        btnSaveEdit.setBackground(new java.awt.Color(81, 141, 245));
        btnSaveEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSaveEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveEdit.setText("Lưu");
        btnSaveEdit.setBorder(null);
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        jlabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabel24.setText("Trạng thái");

        cbbStatusEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cbbStatusEdit.setForeground(new java.awt.Color(255, 51, 51));
        cbbStatusEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hợp tác", "Tạm ngưng" }));

        btnClearEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClearEdit.setForeground(new java.awt.Color(102, 102, 102));
        btnClearEdit.setText("Làm mới");
        btnClearEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEditSupplierLayout = new javax.swing.GroupLayout(pnEditSupplier);
        pnEditSupplier.setLayout(pnEditSupplierLayout);
        pnEditSupplierLayout.setHorizontalGroup(
            pnEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditSupplierLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbIDEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbStatusEdit, 0, 1100, Short.MAX_VALUE)
                    .addComponent(jlabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmailEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addComponent(tfPhoneEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addComponent(tfAdressEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addComponent(jlabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEditSupplierLayout.createSequentialGroup()
                        .addComponent(btnClearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNameEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnEditSupplierLayout.setVerticalGroup(
            pnEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditSupplierLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TablePane.addTab("Chỉnh sửa thông tin", pnEditSupplier);

        pnCategori.add(TablePane);
        TablePane.setBounds(0, 0, 1170, 630);

        pnMain.add(pnCategori);
        pnCategori.setBounds(0, 50, 1180, 630);

        getContentPane().add(pnMain);
        pnMain.setBounds(0, 0, 1180, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSeacrhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSeacrhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSeacrhActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEditActionPerformed
        // TODO add your handling code here:
        reloadForm();
        cbbIDEdit.setEnabled(true);
    }//GEN-LAST:event_btnClearEditActionPerformed
    
    private void btnSaveAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddActionPerformed
        // TODO add your handling code here:
        if(tfNameAdd.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Tên cty không dược trống","",JOptionPane.ERROR_MESSAGE);
                return;
            }
            String rePhone = "^(03|05|07|08|09)\\d{8}$";
            String phone = tfPhoneAdd.getText().trim();
            if (!phone.matches(rePhone)) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NCC.checkPhone(phone,Integer.parseInt(tfIDAdd.getText()))!=0)
            {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String reEmail = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
            String email = tfEmailAdd.getText().trim();
            if (!email.matches(reEmail)) {
                JOptionPane.showMessageDialog(null, "Email không đúng định dạng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NCC.checkEmail(email,Integer.parseInt(tfIDAdd.getText()))!=0)
            {
                JOptionPane.showMessageDialog(null, "Địa chỉ email đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(tfAdressAdd.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Địa chỉ không dược trống","",JOptionPane.ERROR_MESSAGE);
                return;
            }
        NhaCungCap ncc = new NhaCungCap();
        int id = Integer.parseInt(tfIDAdd.getText());
        ncc.setMaNhaCungCap(id);
        ncc.setDiaChi(tfAdressAdd.getText());
        ncc.setEmail(tfEmailAdd.getText());
        ncc.setSoDienThoai(tfPhoneAdd.getText());
        ncc.setTenNcc(tfNameAdd.getText());
        NCC.insert(ncc);
        JOptionPane.showMessageDialog(null, "Tạo nhà cung cấp mới thành công","",JOptionPane.INFORMATION_MESSAGE);
        loadSuppliers();
        loadCombobox();
        clearForm();
    }//GEN-LAST:event_btnSaveAddActionPerformed

    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        // TODO add your handling code here:
         if(tfNameEdit.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Tên cty không dược trống","",JOptionPane.ERROR_MESSAGE);
                return;
            }
            String rePhone = "^(03|05|07|08|09)\\d{8}$";
            String phone = tfPhoneEdit.getText().trim();
            if (!phone.matches(rePhone)) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NCC.checkPhone(phone,Integer.parseInt(cbbIDEdit.getSelectedItem().toString()))!=0)
            {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String reEmail = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
            String email = tfEmailEdit.getText().trim();
            if (!email.matches(reEmail)) {
                JOptionPane.showMessageDialog(null, "Email không đúng định dạng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(NCC.checkEmail(email,Integer.parseInt(cbbIDEdit.getSelectedItem().toString()))!=0)
            {
                JOptionPane.showMessageDialog(null, "Địa chỉ email đã tồn tại trong dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(tfAdressEdit.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Địa chỉ không dược trống","",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        NhaCungCap ncc = new NhaCungCap();
        int id = Integer.parseInt(cbbIDEdit.getSelectedItem().toString());
        ncc.setMaNhaCungCap(id);
        ncc.setDiaChi(tfAdressEdit.getText());
        ncc.setEmail(tfEmailEdit.getText());
        ncc.setSoDienThoai(tfPhoneEdit.getText());
        ncc.setTenNcc(tfNameEdit.getText());
        ncc.setTrangThai(cbbStatusEdit.getSelectedItem().toString());
        NCC.update(ncc);
        loadSuppliers();
        
        JOptionPane.showMessageDialog(null, "Cập nhật thông tin nhà cung cấp thành công","",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnSaveEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier_AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier_AdminScreen(new mainAdminScreen()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTabbedPane TablePane;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearEdit;
    private javax.swing.JButton btnDecor;
    private javax.swing.JButton btnExportFIle;
    private javax.swing.JButton btnSaveAdd;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JComboBox<String> cbbIDEdit;
    private javax.swing.JComboBox<String> cbbSort;
    private javax.swing.JComboBox<String> cbbStatusEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabel18;
    private javax.swing.JLabel jlabel19;
    private javax.swing.JLabel jlabel20;
    private javax.swing.JLabel jlabel21;
    private javax.swing.JLabel jlabel22;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JLabel jlabel24;
    private javax.swing.JLabel jlabel25;
    private javax.swing.JLabel jlabel26;
    private javax.swing.JLabel jlabel27;
    private javax.swing.JLabel jlabel28;
    private javax.swing.JLabel lbTitleList_client;
    private javax.swing.JPanel pnCRUD;
    private javax.swing.JPanel pnCategori;
    private javax.swing.JPanel pnCreateSupplier;
    private javax.swing.JPanel pnEditSupplier;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSupplier;
    private javax.swing.JTable tableSupllier;
    private javax.swing.JTextField tfAdressAdd;
    private javax.swing.JTextField tfAdressEdit;
    private javax.swing.JTextField tfEmailAdd;
    private javax.swing.JTextField tfEmailEdit;
    private javax.swing.JTextField tfIDAdd;
    private javax.swing.JTextField tfNameAdd;
    private javax.swing.JTextField tfNameEdit;
    private javax.swing.JTextField tfPhoneAdd;
    private javax.swing.JTextField tfPhoneEdit;
    private javax.swing.JTextField tfSeacrh;
    // End of variables declaration//GEN-END:variables

    

    private void loadScreen() {
        tfIDAdd.setEditable(false);
        editTable();
        editButton();
        editCombobox();
        loadCombobox();
        editTabTitle(TablePane, pnSupplier, "Danh sách nhà cung cấp", 0);
        editTabTitle(TablePane, pnCreateSupplier, "Thêm nhà cung cấp", 1);
        editTabTitle(TablePane, pnEditSupplier, "Chỉnh sửa thông tin", 2);
        loadSuppliers();
        reloadForm();
        clearForm();
        ItemListener reloadListener = e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                reloadForm();
            }
        };
        cbbIDEdit.addItemListener(reloadListener);
        tfSeacrh.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {loadSuppliers();}
            public void removeUpdate(DocumentEvent e) {loadSuppliers();}
            public void changedUpdate(DocumentEvent e) { loadSuppliers();}
        });
    }

    private void loadCombobox()
    {
        cbbIDEdit.removeAllItems();
        List<NhaCungCap>list = NCC.getAll();
        for(NhaCungCap x : list)
        {
            System.out.println(x.getMaNhaCungCap().toString());
            cbbIDEdit.addItem(x.getMaNhaCungCap().toString());
        }
    }
    private void editCombobox() {
        cbbStatusEdit.setBackground(Color.WHITE);
        ItemListener load = e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                loadSuppliers();
                cbbIDEdit.setEnabled(false);
            }
        };
        cbbSort.addItemListener(load);
        
        
    }

    private void editButton() {
        btnExportFIle.setBackground(Color.WHITE);
        btnDecor.setContentAreaFilled(false);
        btnClear.setContentAreaFilled(false);
    }

    private void editTable() {
        Object[] columnNames = {"Mã NCC", "Tên CTY", "Email", "Điện thoai","Địa chỉ","Trạng thái"};
        model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableSupllier.setModel(model);
        JTableHeader header = tableSupllier.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 14));
        header.setBackground(Color.LIGHT_GRAY);
        header.setForeground(Color.BLACK);
        ((DefaultTableCellRenderer) header.getDefaultRenderer())
            .setHorizontalAlignment(JLabel.CENTER);
               
      
        DefaultTableCellRenderer resetRenderer = new DefaultTableCellRenderer();
        resetRenderer.setHorizontalAlignment(JLabel.CENTER);
        resetRenderer.setForeground(Color.RED);
        resetRenderer.setFont(new Font("Arial", Font.BOLD, 12));
        tableSupllier.getColumn("Mã NCC").setCellRenderer(resetRenderer);
        tableSupllier.getColumn("Trạng thái").setCellRenderer(resetRenderer);
        

    }

    private void editTabTitle(JTabbedPane tabbedPane, JPanel tabPanel, String title, int index) {
        JLabel label = new JLabel(title);
        label.setFont(new java.awt.Font("Arial", 0, 16)); //
        label.setPreferredSize(new Dimension(220, 30));
        tabbedPane.setTabComponentAt(index, label);
    }
}